// Copies provider marks from @lobehub/icons-static-svg into assets/logos/ (white, monochrome, keyed by the
// OpenRouter provider prefix) and generates src/logos.js so both Node and the browser can embed them.
import fs from 'node:fs/promises';
import path from 'node:path';

const SRC = 'node_modules/@lobehub/icons-static-svg/icons';
// OpenRouter provider prefix -> icon file (the mark people recognize for that provider's models)
const MAP = {
  openai: 'openai', anthropic: 'anthropic', google: 'gemini', 'x-ai': 'xai', 'meta-llama': 'meta', mistralai: 'mistral',
  deepseek: 'deepseek', qwen: 'qwen', moonshotai: 'moonshot', 'z-ai': 'zai', cohere: 'cohere', perplexity: 'perplexity',
  nvidia: 'nvidia', microsoft: 'microsoft', amazon: 'bedrock', ai21: 'ai21', minimax: 'minimax', baidu: 'baidu',
  bytedance: 'bytedance', tencent: 'tencent', inception: 'inception', nousresearch: 'nous', liquid: 'liquid', inflection: 'inflection',
};
const out = {};
for (const [prefix, file] of Object.entries(MAP)) {
  let svg;
  try { svg = await fs.readFile(path.join(SRC, `${file}.svg`), 'utf8'); } catch { console.warn(`no icon for ${prefix} (${file}.svg)`); continue; }
  svg = svg
    .replace(/<title>.*?<\/title>/, '')
    .replace(/\s(height|width)="1em"/g, '')
    .replace(/\sstyle="[^"]*"/, '')
    .replace(/currentColor/g, '#ffffff')
    .replace(/\s+/g, ' ')
    .trim();
  await fs.writeFile(`assets/logos/${prefix}.svg`, svg + '\n');
  out[prefix] = svg;
}
const js = `// Generated by scripts/build-logos.mjs from @lobehub/icons-static-svg. Do not edit by hand.
// Marks are trademarks of their owners and are used only to identify the provider of each model.
export const LOGOS = ${JSON.stringify(out, null, 0)};

export function providerOf(modelId) {
  return String(modelId).split('/')[0];
}

/** data: URI for an <image> element, or null when we have no mark for that provider. */
export function logoFor(modelId) {
  const svg = LOGOS[providerOf(modelId)];
  if (!svg) return null;
  const b64 = typeof Buffer !== 'undefined' ? Buffer.from(svg, 'utf8').toString('base64') : btoa(unescape(encodeURIComponent(svg)));
  return 'data:image/svg+xml;base64,' + b64;
}
`;
await fs.writeFile('src/logos.js', js);
console.log(`wrote ${Object.keys(out).length} logos:`, Object.keys(out).join(', '));
